image: java:8-jdk

stages:
  - build
  - package

before_script:
  - wget https://services.gradle.org/distributions/gradle-4.0.1-bin.zip
  - mkdir /opt/gradle
  - unzip -d /opt/gradle gradle-4.0.1-bin.zip
  - export PATH=$PATH:/opt/gradle/gradle-4.0.1/bin
  - gradle -v
  - gradle wrapper
  - chmod +x gradlew

build-project:
  stage: build
  script:
    - ./gradlew build
  only:
    - develop, feature/CHK-013-GitLab-CI-CD

package-jar:
  stage: package
  script:
    - ./gradlew allJar

after_script:
  - echo "Checkers is up"
