image: java:8

stages:
  - build
  - package

before_script:
  - gradle -v
  - chmod +x gradlew

build-project:
  stage: build
  script:
    - ./gradlew build
  only:
    - develop, feature/CHK-013-GitLab-CI-CD

package-jar:
  stage: package
  script:
    - ./gradlew allJar

after_script:
  - echo "Checkers is up"
